"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.UserData = [
    { "name": "Cari Cattrell", "dna": "Southern California Edison Company", "permission": 'Read' },
    { "name": "Shanie Clorley", "dna": "Amedisys Inc", "permission": 'Write' },
    { "name": "Rip Rylatt", "dna": "REX American Resources Corporation", "permission": 'Read' },
    { "name": "Maible Amott", "dna": "Deutsch Bk Contingent Cap Tr V", "permission": 'Write' },
    { "name": "Camila Beetham", "dna": "Scorpio Tankers Inc.", "permission": 'Admin' },
    { "name": "Hayden Pavel", "dna": "Lowe&#39;s Companies, Inc.", "permission": 'Admin' },
    { "name": "Ealasaid Bracknall", "dna": "iShares Fallen Angels USD Bond ETF", "permission": 'Read' },
    { "name": "Lurline Peltzer", "dna": "Neustar, Inc.", "permission": 'Write' },
    { "name": "Linell Whiles", "dna": "Clifton Bancorp Inc.", "permission": 'Write' },
    { "name": "Glyn Heatley", "dna": "Kitov Pharmaceuticals Holdings Ltd.", "permission": 'Admin' },
    { "name": "Trent Jurgen", "dna": "Cytori Therapeutics Inc", "permission": 'Admin' },
    { "name": "Lanie Sandbach", "dna": "Gold Fields Limited", "permission": 'Write' },
    { "name": "Jerrilee Spellsworth", "dna": "Scorpio Tankers Inc.", "permission": 'Read' },
    { "name": "Jewel Turn", "dna": "Patriot National, Inc.", "permission": 'Write' },
    { "name": "Lilli Ganforth", "dna": "Canadian National Railway Company", "permission": 'Admin' },
    { "name": "Nanine Ferreres", "dna": "Lincoln Electric Holdings, Inc.", "permission": 'Admin' },
    { "name": "Mozelle Giorio", "dna": "HV Bancorp, Inc.", "permission": 'Read' },
    { "name": "Bax McCullagh", "dna": "National General Holdings Corp", "permission": 'Write' },
    { "name": "Hirsch Mitten", "dna": "Fifth Third Bancorp", "permission": 'Read' },
    { "name": "Drusy Cubbit", "dna": "Capital Southwest Corporation", "permission": 'Read' },
    { "name": "Frederigo Davidesco", "dna": "Trex Company, Inc.", "permission": 'Write' },
    { "name": "Hanny Skillington", "dna": "EVINE Live Inc.", "permission": 'Read' },
    { "name": "Christye Yeates", "dna": "iRhythm Technologies, Inc.", "permission": 'Write' },
    { "name": "Danila Valente", "dna": "BlackRock Utility and Infrastructure Trust", "permission": 'Write' },
    { "name": "Hedvig Romaint", "dna": "Royal Bank Scotland plc (The)", "permission": 'Write' },
    { "name": "Travus Laxston", "dna": "AmeriServ Financial Inc.", "permission": 'Admin' },
    { "name": "Silvio Carbery", "dna": "Party City Holdco Inc.", "permission": 'Read' },
    { "name": "Thibaud Weale", "dna": "Wells Fargo & Company", "permission": 'Read' },
    { "name": "Romy Scoggan", "dna": "Cyclacel Pharmaceuticals, Inc.", "permission": 'Admin' },
    { "name": "Monty Scaice", "dna": "VanEck Vectors Pharmaceutical ETF", "permission": 'Write' },
    { "name": "Neysa McJury", "dna": "Fairmount Santrol Holdings Inc.", "permission": 'Write' },
    { "name": "Trev Brosetti", "dna": "CBAK Energy Technology, Inc.", "permission": 'Admin' },
    { "name": "Myrlene Armall", "dna": "Textainer Group Holdings Limited", "permission": 'Admin' },
    { "name": "Renelle Chadbourn", "dna": "People&#39;s United Financial, Inc.", "permission": 'Admin' },
    { "name": "Roosevelt Faulks", "dna": "Whiting Petroleum Corporation", "permission": 'Write' },
    { "name": "Aldo Yakushkin", "dna": "PIMCO Dynamic Income Fund", "permission": 'Write' },
    { "name": "Ariel Fowgies", "dna": "Sunshine Bancorp, Inc.", "permission": 'Admin' },
    { "name": "Ermanno Bussen", "dna": "Bank of America Corporation", "permission": 'Write' },
    { "name": "Chilton Beaconsall", "dna": "DHI Group, Inc.", "permission": 'Admin' },
    { "name": "Auria Trahmel", "dna": "Hurco Companies, Inc.", "permission": 'Read' },
    { "name": "Dmitri Edridge", "dna": "Destination XL Group, Inc.", "permission": 'Read' },
    { "name": "Raye Wilman", "dna": "Northern Trust Corporation", "permission": 'Admin' },
    { "name": "Rodger Tunstall", "dna": "HC2 Holdings, Inc.", "permission": 'Admin' },
    { "name": "Mariam Stuehmeyer", "dna": "iShares S&P Emerging Markets Infrastructure Index Fund", "permission": 'Admin' },
    { "name": "Farrand Creagh", "dna": "Avis Budget Group, Inc.", "permission": 'Read' },
    { "name": "Tallie Cyphus", "dna": "Biomerica, Inc.", "permission": 'Read' },
    { "name": "Ahmad Archbould", "dna": "Lumber Liquidators Holdings, Inc", "permission": 'Read' },
    { "name": "Geno Dillamore", "dna": "Marlin Business Services Corp.", "permission": 'Read' },
    { "name": "Eydie Crockford", "dna": "Houghton Mifflin Harcourt Company", "permission": 'Read' },
    { "name": "Abbie Stubbin", "dna": "Nathan&#39;s Famous, Inc.", "permission": 'Write' },
    { "name": "Alejandro Fabbro", "dna": "Inogen, Inc", "permission": 'Write' },
    { "name": "Rheba Bee", "dna": "First Busey Corporation", "permission": 'Admin' },
    { "name": "Willy Wardlow", "dna": "Nordic American Offshore Ltd", "permission": 'Read' },
    { "name": "Wesley De Zamudio", "dna": "Onconova Therapeutics, Inc.", "permission": 'Write' },
    { "name": "Reinhold Koschek", "dna": "NextEra Energy, Inc.", "permission": 'Write' },
    { "name": "Dare Rippingall", "dna": "Liberty TripAdvisor Holdings, Inc.", "permission": 'Admin' },
    { "name": "Dre Kelston", "dna": "Blackrock Health Sciences Trust", "permission": 'Read' },
    { "name": "Correy Stetlye", "dna": "RigNet, Inc.", "permission": 'Read' },
    { "name": "Rutledge Spary", "dna": "First Bank", "permission": 'Admin' },
    { "name": "Tades O'Lunny", "dna": "Agilysys, Inc.", "permission": 'Admin' },
    { "name": "Hyman Thomesson", "dna": "CYS Investments, Inc.", "permission": 'Read' },
    { "name": "Tadd Ethridge", "dna": "United-Guardian, Inc.", "permission": 'Read' },
    { "name": "Herold Basten", "dna": "Cempra, Inc.", "permission": 'Read' },
    { "name": "Mellie Issac", "dna": "Armstrong Flooring, Inc.", "permission": 'Write' },
    { "name": "Pernell McLachlan", "dna": "Service Corporation International", "permission": 'Admin' },
    { "name": "Sashenka Dews", "dna": "Putnam Master Intermediate Income Trust", "permission": 'Read' },
    { "name": "Dorise Varndell", "dna": "voxeljet AG", "permission": 'Admin' },
    { "name": "Lauren Jaquemar", "dna": "Gladstone Investment Corporation", "permission": 'Admin' },
    { "name": "Joscelin Mulheron", "dna": "NAPCO Security Technologies, Inc.", "permission": 'Read' },
    { "name": "Berty Dartnell", "dna": "ContraVir Pharmaceuticals Inc", "permission": 'Read' },
    { "name": "Mac Fargie", "dna": "Customers Bancorp, Inc", "permission": 'Write' },
    { "name": "Thatch Badrick", "dna": "Callon Petroleum Company", "permission": 'Admin' },
    { "name": "Nariko Roseveare", "dna": "Akebia Therapeutics, Inc.", "permission": 'Read' },
    { "name": "Swen Scandrett", "dna": "Perceptron, Inc.", "permission": 'Admin' },
    { "name": "Sarah Heaven", "dna": "Bank of America Corporation", "permission": 'Write' },
    { "name": "Maggie Flecknoe", "dna": "Aetna Inc.", "permission": 'Write' },
    { "name": "Raddy Pinock", "dna": "Arlington Asset Investment Corp", "permission": 'Read' },
    { "name": "Lorrie Penella", "dna": "Signature Bank", "permission": 'Admin' },
    { "name": "Roddy Bastable", "dna": "Endurance International Group Holdings, Inc.", "permission": 'Admin' },
    { "name": "Maure Footer", "dna": "Playa Hotels & Resorts N.V.", "permission": 'Write' },
    { "name": "Marnie Rabidge", "dna": "MSA Safety Incorporporated", "permission": 'Admin' },
    { "name": "Sib Maclaine", "dna": "Equity Lifestyle Properties, Inc.", "permission": 'Write' },
    { "name": "Kippy Oselton", "dna": "Mizuho Financial Group, Inc.", "permission": 'Admin' },
    { "name": "Gipsy Challicum", "dna": "ATA Inc.", "permission": 'Write' },
    { "name": "Jesse Giacovazzo", "dna": "Agrium Inc.", "permission": 'Read' },
    { "name": "Alika Watting", "dna": "Firsthand Technology Value Fund, Inc.", "permission": 'Admin' },
    { "name": "Brod Gregorin", "dna": "Huttig Building Products, Inc.", "permission": 'Admin' },
    { "name": "Misha Chifney", "dna": "Cleantech Solutions International, Inc.", "permission": 'Write' },
    { "name": "Zollie Weed", "dna": "Stock Yards Bancorp, Inc.", "permission": 'Admin' },
    { "name": "Lucille Keizman", "dna": "Marathon Oil Corporation", "permission": 'Write' },
    { "name": "Garvin Lynam", "dna": "Videocon d2h Limited", "permission": 'Write' },
    { "name": "Leilah MacGilmartin", "dna": "J & J Snack Foods Corp.", "permission": 'Read' },
    { "name": "Fayth Chesman", "dna": "Mesa Laboratories, Inc.", "permission": 'Read' },
    { "name": "Modesty Kiezler", "dna": "America Movil, S.A.B. de C.V.", "permission": 'Read' },
    { "name": "Felix Laughlan", "dna": "Crestwood Equity Partners LP", "permission": 'Write' },
    { "name": "Manolo Stubbert", "dna": "U.S. Bancorp", "permission": 'Read' },
    { "name": "Erie Angear", "dna": "Malibu Boats, Inc.", "permission": 'Write' },
    { "name": "Cherin Culligan", "dna": "Cleveland BioLabs, Inc.", "permission": 'Write' },
    { "name": "Traver Flores", "dna": "Zoetis Inc.", "permission": 'Write' },
    { "name": "Jeffrey Raoux", "dna": "Deere & Company", "permission": 'Admin' },
    { "name": "Debi Meysham", "dna": "Companhia Brasileira de Distribuicao", "permission": 'Read' },
    { "name": "Hendrick Yurlov", "dna": "IF Bancorp, Inc.", "permission": 'Write' },
    { "name": "Hobie Meaking", "dna": "LM Funding America, Inc.", "permission": 'Read' },
    { "name": "Tonie Baldin", "dna": "Investors Bancorp, Inc.", "permission": 'Write' },
    { "name": "Zechariah Sneyd", "dna": "BlackRock 2022 Global Income Opportunity Trust", "permission": 'Read' },
    { "name": "Cybil Selwyn", "dna": "Immersion Corporation", "permission": 'Admin' },
    { "name": "Isaak Blackaller", "dna": "BlackRock Income Investment Quality Trust", "permission": 'Admin' },
    { "name": "Ker Frayling", "dna": "Advaxis, Inc.", "permission": 'Write' },
    { "name": "Tulley Golightly", "dna": "CDI Corporation", "permission": 'Write' },
    { "name": "Trudie Janecki", "dna": "Kronos Worldwide Inc", "permission": 'Write' },
    { "name": "Abbye Ledgister", "dna": "Pennsylvania Real Estate Investment Trust", "permission": 'Write' },
    { "name": "Mannie Pincked", "dna": "Eaton Vance Short Diversified Income Fund", "permission": 'Admin' },
    { "name": "Walton Fazackerley", "dna": "KB Financial Group Inc", "permission": 'Read' },
    { "name": "Georgy Hayto", "dna": "Dynex Capital, Inc.", "permission": 'Write' },
    { "name": "Ade Dibb", "dna": "Steel Dynamics, Inc.", "permission": 'Read' },
    { "name": "Deny Burdikin", "dna": "Federated Investors, Inc.", "permission": 'Admin' },
    { "name": "Marie Simms", "dna": "Nationstar Mortgage Holdings Inc.", "permission": 'Write' },
    { "name": "Bernardo Whooley", "dna": "Medley Management Inc.", "permission": 'Admin' },
    { "name": "Nicolina McGilleghole", "dna": "MFS Charter Income Trust", "permission": 'Admin' },
    { "name": "Ricca Blowne", "dna": "M III Acquisition Corp.", "permission": 'Admin' },
    { "name": "Verina Seys", "dna": "HV Bancorp, Inc.", "permission": 'Admin' },
    { "name": "Bekki Cobbledick", "dna": "West Corporation", "permission": 'Read' },
    { "name": "Beilul Groome", "dna": "Eaton Vance Municipal Income 2028 Term Trust", "permission": 'Write' },
    { "name": "Tybalt Elan", "dna": "Navient Corporation", "permission": 'Read' },
    { "name": "Arman Brimley", "dna": "Global X Yieldco Index ETF", "permission": 'Admin' },
    { "name": "Filia Castellucci", "dna": "Coca-Cola European Partners plc", "permission": 'Admin' },
    { "name": "Emilia Lympenie", "dna": "ENI S.p.A.", "permission": 'Write' },
    { "name": "Nathanil Hartman", "dna": "Colony NorthStar, Inc.", "permission": 'Admin' },
    { "name": "Derry Clowney", "dna": "Goldman Sachs Group, Inc. (The)", "permission": 'Write' },
    { "name": "Kingston Stirman", "dna": "Willis Towers Watson Public Limited Company", "permission": 'Admin' },
    { "name": "Aleece Botwright", "dna": "Hamilton Bancorp, Inc.", "permission": 'Admin' },
    { "name": "Clevie Girardey", "dna": "Eastman Kodak Company", "permission": 'Read' },
    { "name": "Syd Betser", "dna": "Auburn National Bancorporation, Inc.", "permission": 'Read' },
    { "name": "Deck Goddert.sf", "dna": "Ashford Hospitality Trust Inc", "permission": 'Read' },
    { "name": "Xymenes Blazej", "dna": "First Trust High Income Long Short Fund", "permission": 'Write' },
    { "name": "Germain Guerreiro", "dna": "Mercer International Inc.", "permission": 'Write' },
    { "name": "Rodrigo Hulls", "dna": "Biohaven Pharmaceutical Holding Company Ltd.", "permission": 'Admin' },
    { "name": "Trista Tackes", "dna": "Davis Select Worldwide ETF", "permission": 'Admin' },
    { "name": "Briana Zealander", "dna": "Omega Healthcare Investors, Inc.", "permission": 'Admin' },
    { "name": "Aggi Tassell", "dna": "Bank of South Carolina Corp.", "permission": 'Write' },
    { "name": "Willi Spurritt", "dna": "Century Bancorp, Inc.", "permission": 'Write' },
    { "name": "Kristal Lawry", "dna": "JM Global Holding Company", "permission": 'Admin' },
    { "name": "Halli Murrish", "dna": "CorVel Corp.", "permission": 'Read' },
    { "name": "Pepe Ruvel", "dna": "Blackrock MuniYield Quality Fund III, Inc.", "permission": 'Admin' },
    { "name": "Alic Tidbury", "dna": "M III Acquisition Corp.", "permission": 'Admin' },
    { "name": "Zonnya Tame", "dna": "Impax Laboratories, Inc.", "permission": 'Write' },
    { "name": "Alford Berrygun", "dna": "Capstead Mortgage Corporation", "permission": 'Write' },
    { "name": "Mirella Playford", "dna": "Fossil Group, Inc.", "permission": 'Read' },
    { "name": "Upton Pryell", "dna": "Employers Holdings Inc", "permission": 'Read' },
    { "name": "Corny Gierke", "dna": "Townsquare Media, Inc.", "permission": 'Admin' },
    { "name": "Laina Falvey", "dna": "First Savings Financial Group, Inc.", "permission": 'Admin' },
    { "name": "Faythe Spencley", "dna": "Ferroglobe PLC", "permission": 'Admin' },
    { "name": "Gwenore Tocque", "dna": "Enbridge Energy Management LLC", "permission": 'Write' },
    { "name": "Erika Jull", "dna": "Modern Media Acquisition Corp.", "permission": 'Read' },
    { "name": "Wilmer Filipczak", "dna": "Home Bancorp, Inc.", "permission": 'Admin' },
    { "name": "Logan Dauber", "dna": "Xenon Pharmaceuticals Inc.", "permission": 'Read' },
    { "name": "Rochell Gullberg", "dna": "Banco Santander, S.A.", "permission": 'Write' },
    { "name": "Kimble McKirdy", "dna": "iFresh Inc.", "permission": 'Write' },
    { "name": "Zia Souza", "dna": "DRDGOLD Limited", "permission": 'Write' },
    { "name": "Brinn Gouny", "dna": "American Electric Power Company, Inc.", "permission": 'Read' },
    { "name": "Abigail Jellings", "dna": "Atrion Corporation", "permission": 'Write' },
    { "name": "Lane Jozsika", "dna": "Sify Technologies Limited", "permission": 'Write' },
    { "name": "Forster Harpham", "dna": "Coca-Cola Company (The)", "permission": 'Write' },
    { "name": "Nona Stork", "dna": "Hancock Holding Company", "permission": 'Admin' },
    { "name": "Mariel Archanbault", "dna": "Univest Corporation of Pennsylvania", "permission": 'Write' },
    { "name": "Lorin Ackerley", "dna": "THL Credit Senior Loan Fund", "permission": 'Read' },
    { "name": "Giuseppe Risby", "dna": "The Ensign Group, Inc.", "permission": 'Admin' },
    { "name": "Ilyse Gellion", "dna": "SandRidge Mississippian Trust II", "permission": 'Admin' },
    { "name": "Fulvia Argo", "dna": "Aduro Biotech, Inc.", "permission": 'Admin' },
    { "name": "Else Aldins", "dna": "V.F. Corporation", "permission": 'Write' },
    { "name": "Amalita Bugdall", "dna": "RCM Technologies, Inc.", "permission": 'Admin' },
    { "name": "Vitia Chalcroft", "dna": "Cohen & Steers Total Return Realty Fund, Inc.", "permission": 'Admin' },
    { "name": "Leigh Beddis", "dna": "First Trust NASDAQ-100 Equal Weighted Index Fund", "permission": 'Write' },
    { "name": "Saudra Janeczek", "dna": "Agenus Inc.", "permission": 'Read' },
    { "name": "Phillida Hennington", "dna": "DaVita Inc.", "permission": 'Admin' },
    { "name": "Wallie McIlwreath", "dna": "Gabelli Utility Trust (The)", "permission": 'Read' },
    { "name": "Dede Doring", "dna": "The Obesity ETF", "permission": 'Admin' },
    { "name": "Averell Dorro", "dna": "VTTI Energy Partners LP", "permission": 'Read' },
    { "name": "Patin Twydell", "dna": "WideOpenWest, Inc.", "permission": 'Read' },
    { "name": "Sidnee Mackrell", "dna": "TOR Minerals International Inc", "permission": 'Admin' },
    { "name": "Lemmie Maciejak", "dna": "Prudential Public Limited Company", "permission": 'Read' },
    { "name": "Stacy McNeilley", "dna": "Hoegh LNG Partners LP", "permission": 'Read' },
    { "name": "Paige Sywell", "dna": "Nuveen Short Duration Credit Opportunities Fund", "permission": 'Read' },
    { "name": "Alberta Eilhermann", "dna": "Liberty Media Corporation", "permission": 'Read' },
    { "name": "Ase Solman", "dna": "Wesco Aircraft Holdings, Inc.", "permission": 'Write' },
    { "name": "Fairfax Kittley", "dna": "Southern Company (The)", "permission": 'Read' },
    { "name": "Gert Millership", "dna": "Huron Consulting Group Inc.", "permission": 'Read' },
    { "name": "Robinson Moles", "dna": "Blackrock MuniYield New York Quality Fund, Inc.", "permission": 'Read' },
    { "name": "Pablo Lawrenceson", "dna": "Royal Bank Scotland plc (The)", "permission": 'Write' },
    { "name": "Katleen Lindenbaum", "dna": "Wynn Resorts, Limited", "permission": 'Admin' },
    { "name": "Olive Cescotti", "dna": "Waddell & Reed Financial, Inc.", "permission": 'Admin' },
    { "name": "Jobi Cressey", "dna": "Professional Diversity Network, Inc.", "permission": 'Admin' },
    { "name": "Jasmine Roller", "dna": "Coca-Cola European Partners plc", "permission": 'Admin' },
    { "name": "Magda Gorgler", "dna": "Five Star Senior Living Inc.", "permission": 'Read' },
    { "name": "Bernelle Laurentino", "dna": "NiSource, Inc", "permission": 'Write' },
    { "name": "Gregor Bonifazio", "dna": "Connecticut Water Service, Inc.", "permission": 'Read' },
    { "name": "Vasily Senten", "dna": "Bruker Corporation", "permission": 'Admin' },
    { "name": "Hilary Pee", "dna": "athenahealth, Inc.", "permission": 'Admin' },
    { "name": "Findley Jilliss", "dna": "Inovalon Holdings, Inc.", "permission": 'Read' },
    { "name": "Opal Ourry", "dna": "Champions Oncology, Inc.", "permission": 'Read' },
    { "name": "Yves Dovinson", "dna": "Wyndham Worldwide Corp", "permission": 'Write' },
    { "name": "Nady Birchill", "dna": "Telecom Italia S.P.A.", "permission": 'Read' },
    { "name": "Farlee Risman", "dna": "Iron Mountain Incorporated", "permission": 'Write' },
    { "name": "Jana Hillyatt", "dna": "Physicians Realty Trust", "permission": 'Write' },
    { "name": "Ryun Wymer", "dna": "Reliv&#39; International, Inc.", "permission": 'Read' },
    { "name": "Giustino Curran", "dna": "UFP Technologies, Inc.", "permission": 'Admin' },
    { "name": "Amos Petford", "dna": "Owens & Minor, Inc.", "permission": 'Read' },
    { "name": "Karissa Greeves", "dna": "CHS Inc", "permission": 'Read' },
    { "name": "Wilma Fritchly", "dna": "Dover Motorsports, Inc.", "permission": 'Admin' },
    { "name": "Robbert Malek", "dna": "Ames National Corporation", "permission": 'Admin' },
    { "name": "Creighton Leborgne", "dna": "BSB Bancorp, Inc.", "permission": 'Write' },
    { "name": "Rosalie Swanton", "dna": "IZEA Inc.", "permission": 'Admin' },
    { "name": "Bronny Leopold", "dna": "Oil-Dri Corporation Of America", "permission": 'Read' },
    { "name": "Georgiana Rochelle", "dna": "SandRidge Energy, Inc.", "permission": 'Read' },
    { "name": "Zuzana Loftin", "dna": "First Trust Taiwan AlphaDEX Fund", "permission": 'Read' },
    { "name": "Francklyn Dolden", "dna": "Team, Inc.", "permission": 'Read' },
    { "name": "Lancelot Mithun", "dna": "Goldman Sachs BDC, Inc.", "permission": 'Admin' },
    { "name": "Melisandra Fleetwood", "dna": "Capitol Acquisition Corp. III", "permission": 'Read' },
    { "name": "Betti Lipmann", "dna": "Ambac Financial Group, Inc.", "permission": 'Admin' },
    { "name": "Belvia Brumble", "dna": "Eaton Vance Senior Income Trust", "permission": 'Admin' },
    { "name": "Leoline Wolledge", "dna": "ATN International, Inc.", "permission": 'Admin' },
    { "name": "Olivette Creavan", "dna": "OFG Bancorp", "permission": 'Read' },
    { "name": "Sue Betjes", "dna": "Banco Bradesco Sa", "permission": 'Write' },
    { "name": "Averil Liepmann", "dna": "OFS Capital Corporation", "permission": 'Read' },
    { "name": "Celestyna Ailmer", "dna": "Hawaiian Electric Industries, Inc.", "permission": 'Write' },
    { "name": "Karney Reymers", "dna": "Hamilton Lane Incorporated", "permission": 'Read' },
    { "name": "Beverley Say", "dna": "PayPal Holdings, Inc.", "permission": 'Write' },
    { "name": "Blakeley Calken", "dna": "Global Indemnity Limited", "permission": 'Read' },
    { "name": "Yurik Mityashin", "dna": "National Holdings Corporation", "permission": 'Admin' },
    { "name": "Beverly Fairebrother", "dna": "Dover Motorsports, Inc.", "permission": 'Read' },
    { "name": "Laurella Blazy", "dna": "Fifth Street Senior Floating Rate Corp.", "permission": 'Read' },
    { "name": "Cointon Clucas", "dna": "Savara, Inc.", "permission": 'Admin' },
    { "name": "Cathryn Stennet", "dna": "QuinStreet, Inc.", "permission": 'Admin' },
    { "name": "Eda Stothard", "dna": "Evolent Health, Inc", "permission": 'Write' },
    { "name": "Lari Szachniewicz", "dna": "Tarena International, Inc.", "permission": 'Admin' },
    { "name": "Denise Hopewell", "dna": "Automatic Data Processing, Inc.", "permission": 'Read' },
    { "name": "Floyd Gibling", "dna": "Equity Residential", "permission": 'Write' },
    { "name": "Jeff Fanshaw", "dna": "Brookline Bancorp, Inc.", "permission": 'Write' },
    { "name": "Stuart Milmith", "dna": "Soligenix, Inc.", "permission": 'Read' },
    { "name": "Lauritz Evers", "dna": "Putnam Managed Municipal Income Trust", "permission": 'Read' },
    { "name": "Hillel O'Fallowne", "dna": "Interlink Electronics, Inc.", "permission": 'Admin' },
    { "name": "Tildy Readman", "dna": "Atlassian Corporation Plc", "permission": 'Admin' },
    { "name": "Percy Guidone", "dna": "TechnipFMC plc", "permission": 'Write' },
    { "name": "Harper Dring", "dna": "Public Storage", "permission": 'Write' },
    { "name": "Wallie Drake", "dna": "Aceto Corporation", "permission": 'Write' },
    { "name": "Yuma Have", "dna": "Cenovus Energy Inc", "permission": 'Write' },
    { "name": "Esta Juste", "dna": "Kimbell Royalty Partners", "permission": 'Write' },
    { "name": "Hanny Cowperthwaite", "dna": "Fidelity and Guaranty Life", "permission": 'Admin' },
    { "name": "Carin Pickerell", "dna": "Ion Geophysical Corporation", "permission": 'Read' },
    { "name": "Myrle Suff", "dna": "Spartan Motors, Inc.", "permission": 'Admin' }
];
//# sourceMappingURL=dumydata.js.map